name = "soundcloud-downloader-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Environment variables will be configured in the Cloudflare Dashboard
# Do not put actual tokens here
[vars]
TELEGRAM_BOT_TOKEN = ""    # Configure this in Cloudflare Dashboard

[build]
command = "npm install"  # or "yarn install" if using yarn
watch_dir = "src"

[triggers]
crons = []

# Production environment settings
[env.production]
workers_dev = true
route = ""

# Staging environment settings
[env.staging]
workers_dev = true

# Local development settings
[miniflare]
kv_persist = true
env_path = ".env"        # Use .env file for local development 