name = "soundcloud-downloader-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
# These values will be replaced with your actual credentials in the Cloudflare Dashboard
BOT_TOKEN = ""
SOUNDCLOUD_CLIENT_ID = ""

[[kv_namespaces]]
binding = "BOT_STORAGE"
id = ""
preview_id = ""

[build]
command = "npm install"
watch_dir = "src"

[triggers]
crons = []

[env.production]
workers_dev = true
route = ""

[env.staging]
workers_dev = true

[miniflare]
kv_persist = true
env_path = ".env" 